### ISSUE TITLE
nnode = max(s);

### ISSUE THREAD

**Issue by ajayo17** [kakearney/pathbetweennodes-pkg#1]
I think we must take s or t whichever is greater...

any suggestions/comments?

**Comment by kakearney** [comment]
I assume you're referring to the example in the README?  If so, yes, for a generic case, when building an adjacency matrix from a list of source and target indices, you'd want to make sure you defined the number of nodes based on the highest index.  In this particular example, all nodes were used as both source and target nodes for at least one edge, so I was able to skip the extra calculation.
