### ISSUE TITLE
Print the value of Sparse Matrix as well 

### ISSUE THREAD

**Issue by eragonngo** [kakearney/pathbetweennodes-pkg#2]
Dear Miss Kearney, 

I have found your code via Matlab File Exchange and it works perfectly fine. But I wonder how can you print the value attached to the Sparse Matrix as well in this case as cell format. 

Thank you Miss for your time and concern reading my email, 

Sincerely,

**Comment by kakearney** [comment]
Do you mean you want to return the edge values/weights associated with each path?  To do that, you simply need to extract the edge index associated with each pair of consecutive nodes.

Using the same example as in the README, but with varying edge weights:

```matlab
s = [1 1 2 3 3 4 4 6 6 7 8 7 5]';
t = [2 3 4 4 5 5 6 1 8 1 3 2 8]';

nnode = max(s);
nedge = length(s);

adj = sparse(s,t,1:nedge,nnode,nnode);

pth = pathbetweennodes(adj,7,8);
```

Now loop over each path and get the edge weights:

```matlab
edgval = cell(size(pth));
for ip = 1:length(pth)
    eidx = sub2ind(size(adj), pth{ip}(1:end-1), pth{ip}(2:end));
    edgval{ip} = full(adj(eidx)); 
    % Note: dense sparse matrices are a waste of memory, hence we convert back to full here
end
```

**Comment by eragonngo** [comment]
Thank you so much for your time !!!!
