### ISSUE TITLE
Saving a cell array containing all paths from each node to another

### ISSUE THREAD

**Issue by sinaebrahimi** [kakearney/pathbetweennodes-pkg#3]
Hi, I was wondering if you could help. thanks for the great work.
I have an adj matrix. I just need a cell array containing all possible paths from each node to another, so that I can use it later in my algorithm. 
In fact, I want the cell array to look like this:
1to1  | 1to2      | ...  | 4to3    | 4to4
{}       | {1,2}       | ... | {4,3}     | {}
         | {1,4,2}    | ... | {4,1}     |
         | {1,4,3,2} | ... | {4,2}     |
         |               | ... | {4,3,2} |
         |               | ... | {4,1,2} |
         |               | ... | ...        |

**Comment by sinaebrahimi** [comment]
I mean the real problem is we don't know how many paths each column would have

**Comment by kakearney** [comment]
I’d just suggest setting up a cell array and then looping over the possible source/sink pairs. No need to know how big each cell element will be. 

```matlab
pth = cell(nnode);
for isrc = 1:nnode
    for itar = 1:nnode
        pth{isrc,itar} = pathbetweennodes(adj, isrc, itar);
    end
end
```

**Comment by sinaebrahimi** [comment]
Thank you, man... Your help meant a lot to me.
